name: update release
on:
  workflow_dispatch:
jobs:
  update-release:
    runs-on: ubuntu-latest
#    permissions:
#      contents: write # 書き込むために必要
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go 1.21.3
        uses: actions/setup-go@v4
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.3'
      - name: info
        run: |
          echo pwd; pwd
          echo ls; ls -al
          echo find; find $(pwd) -type f
      - name: test
        run: |
          go test ./...
      - name: push to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         bash ./scripts/build.sh

